# -*- coding: utf-8 -*-
"""Untitled198.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WesbhvQFKhot1C6pe9I5HCnQkVP8oJly
"""

# Clone your repo
!git clone https://github.com/tydeptrai21042004/checkvisualization

%cd checkvisualization

# Optional: upgrade pip a bit
!pip install --upgrade pip

# Make sure torch/torchvision exist (Colab normally has them already)
!pip install torch torchvision --quiet

# Install project requirements (YOLOv5 via ultralytics, OpenCV, torchreid, etc.)
!pip install -r requirements.txt --quiet

# (Optional) inspect your test video
!ls -lh test.mp4

# Fix numpy deprecations in sort.py (still used by some scripts)
!sed -i 's/np.int0(/np.array(/g' sort.py
!sed -i 's/np.array(np.concatenate(ret))/np.array(np.concatenate(ret), dtype=int)/g' sort.py

!sed -n '240,280p' sort.py

# Make sure output folder exists
!mkdir -p epfl

# -------------------------------
# Run SINGLE-CAMERA + ROI tracking
# -------------------------------
# ROI = "x1,y1,x2,y2" in image coordinates
# -> change numbers to match your region in the video
ROI = "400,200,1200,700"

!python main_colab.py \
  --video1 test.mp4 \
  --roi "$ROI" \
  --no-display \
  --save-video epfl/mc_mot_output.mp4

# Check output
!ls -lh epfl
%ls

# Copy video to Google Drive
from google.colab import drive
drive.mount('/content/drive')

import os, shutil

src = "epfl/mc_mot_output.mp4"  # your output path
dst_dir = "/content/drive/MyDrive/EPFL_MOT"  # change folder name if you like
os.makedirs(dst_dir, exist_ok=True)

dst = os.path.join(dst_dir, os.path.basename(src))
shutil.copy(src, dst)

print("Copied to:", dst)

# Also offer direct download
from google.colab import files
files.download("epfl/mc_mot_output.mp4")
